language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

compiler:
  - gcc
  - clang

env:
  - CC=gcc
  - CC=clang

install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt

script:
  - python setup.py test
